framework:
    cache:
        app: cache.adapter.filesystem
        
        pools:
            # Cache pour les données météorologiques
            weather.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600  # 1 heure
            
            # Cache pour les horoscopes
            horoscope.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600  # 1 heure
            
            # Cache pour l'authentification
            auth.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400  # 24 heures
                
            # Cache simplifié pour NelmioApiDoc
            nelmio_api_doc.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600