nelmio_api_doc:
    documentation:
        info:
            title: AstroAPI
            description: API pour la gestion des données astronomiques et horoscopes
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc)