controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
<<<<<<< HEAD
=======

api_login_check:
    path: /api/login_check
    methods: ['POST']
>>>>>>> origin/nolan_back
